---
apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  selector:
    app.kubernetes.io/name: analytics-api
  ports:
    - name: "5151"
      protocol: TCP
      port: 5151
      targetPort: 5151
